//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class cleanup {
        
        // <realm>Server</realm>
        // <summary>Adds an entity to a player's cleanup list.</summary>
        // <param name="pl">Who's cleanup list to add the entity to.</param>
        // <param name="type">The type of cleanup.</param>
        // <param name="ent">The entity to add to the player's cleanup list.</param>
        public virtual void Add(Player pl, string type, Entity ent) {
        }
        
        // <realm>Server</realm>
        // <summary>An internal function that is called by the "gmod_admin_cleanup" console command. Allows admins to clean up the server</summary>
        public virtual void CC_AdminCleanup() {
        }
        
        // <realm>Server</realm>
        // <summary>An internal function that is called by the "gmod_cleanup" console command. Allows players to cleanup their own props.</summary>
        public virtual void CC_Cleanup() {
        }
        
        // <realm>Server</realm>
        // <summary>Gets the cleanup list.</summary>
        public virtual void GetList() {
        }
        
        // <realm>Shared</realm>
        // <summary>Gets the table of cleanup types.</summary>
        // <return>table|cleanup_types</return>
        public virtual table GetTable() {
            return new table();
        }
        
        // <realm>Shared</realm>
        // <summary>Registers a new cleanup type.</summary>
        // <param name="type">Name of type.</param>
        public virtual void Register(string type) {
        }
        
        // <realm>Server</realm>
        // <summary>Replaces one entity in the cleanup module with another</summary>
        // <param name="from">Old entity.</param>
        // <param name="to">New entity.</param>
        // <return>boolean|Whether any action was taken.</return>
        public virtual bool ReplaceEntity(Entity from, Entity to) {
            return true;
        }
        
        // <realm>Client</realm>
        // <summary>Repopulates the clients cleanup menu</summary>
        public virtual void UpdateUI() {
        }
    }
}
