//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class concommand {
        
        // <realm>Shared</realm>
        // <summary>Creates a console command that runs a function in lua with optional autocompletion function and help text.</summary>
        // <param name="name">The command name to be used in console.</param>
        // <param name="commandFunc">The function to run when the concommand is executed.<br>.</param>
        // <param name="autoCompleteFunc">The function to call which should return a table of options for autocompletion.<br>.</param>
        // <param name="helpText">The text to display should a user run 'help cmdName'.</param>
        // <param name="flags">Concommand flags from {{Enum|FCVAR}}.</param>
        public virtual void Add(string name, function commandFunc, function autoCompleteFunc, string helpText, float flags) {
        }
        
        // <realm>Shared</realm>
        // <summary>Returns a table for the autocompletion</summary>
        public virtual table AutoComplete() {
            return new table();
        }
        
        // <realm>Shared</realm>
        // <summary>Returns a table of all the console commands that were added to the game via lua.</summary>
        // <return>table|Table of commands.</return>
        public virtual table GetTable() {
            return new table();
        }
        
        // <realm>Shared</realm>
        // <summary>Removes a console command.</summary>
        // <param name="name">The command name to be used in console.</param>
        public virtual void Remove(string name) {
        }
        
        // <realm>Shared</realm>
        // <summary>{{Internal}}</summary>
        // <param name="ply">Player to run concommand on.</param>
        // <param name="cmd">Command name.</param>
        // <param name="args">Command arguments.</param>
        // <return>boolean|Return value</return>
        public virtual bool Run(Player ply, string cmd, any args) {
            return true;
        }
    }
}
