//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class cookie {
        
        // <realm>Client</realm>
        // <summary>Deletes a cookie on the client.</summary>
        // <param name="name">The name of the cookie that you want to delete.</param>
        public virtual void Delete(string name) {
        }
        
        // <realm>Client</realm>
        // <summary>Gets the value of a cookie on the client as a number.</summary>
        // <param name="name">The name of the cookie that you want to get.</param>
        // <param name="default">Value to return if the cookie does not exist.</param>
        // <return>number|The cookie value</return>
        public virtual int GetNumber(string name, float @default) {
            return 1;
        }
        
        // <realm>Client</realm>
        // <summary>Gets the value of a cookie on the client as a string.</summary>
        // <param name="name">The name of the cookie that you want to get.</param>
        // <param name="default">Value to return if the cookie does not exist.</param>
        // <return>string|The cookie value</return>
        public virtual string GetString(string name, string @default) {
            return "String";
        }
        
        // <realm>Client</realm>
        // <summary>Sets the value of a cookie on the client.<br /></summary>
        // <param name="key">The name of the cookie that you want to set.</param>
        // <param name="value">Value to store in the cookie.</param>
        public virtual void Set(string key, string value) {
        }
    }
}
