//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class GWEN {
        
        // <realm>Client</realm>
        // <summary>Used in derma skins to create a bordered rectangle drawing function from an image. The texture is taken from SKIN.GwenTexture</summary>
        // <param name="x">The X coordinate on the texture.</param>
        // <param name="y">The Y coordinate on the texture.</param>
        // <param name="w">Width of the area on texture.</param>
        // <param name="h">Height of the area on texture.</param>
        // <param name="left">Left width of border.</param>
        // <param name="top">Top width of border.</param>
        // <param name="right">Right width of border.</param>
        // <param name="bottom">Bottom width of border.</param>
        // <return>function|The drawing function. Arguments are:</return>
        public virtual function CreateTextureBorder(float x, float y, float w, float h, float left, float top, float right, float bottom) {
            return new function();
        }
        
        // <realm>Client</realm>
        // <summary>Used in derma skins to create a rectangle drawing function from an image. The rectangle will not be scaled, but instead it will be drawn in the center of the box. The texture is taken from SKIN.GwenTexture</summary>
        // <param name="x">The X coordinate on the texture.</param>
        // <param name="y">The Y coordinate on the texture.</param>
        // <param name="w">Width of the area on texture.</param>
        // <param name="h">Height of the area on texture.</param>
        // <return>function|The drawing function. Arguments are:</return>
        public virtual function CreateTextureCentered(float x, float y, float w, float h) {
            return new function();
        }
        
        // <realm>Client</realm>
        // <summary>Used in derma skins to create a rectangle drawing function from an image. The texture of the rectangle will be scaled. The texture is taken from SKIN.GwenTexture</summary>
        // <param name="x">The X coordinate on the texture.</param>
        // <param name="y">The Y coordinate on the texture.</param>
        // <param name="w">Width of the area on texture.</param>
        // <param name="h">Height of the area on texture.</param>
        // <return>function|The drawing function. Arguments are:</return>
        public virtual function CreateTextureNormal(float x, float y, float w, float h) {
            return new function();
        }
        
        // <realm>Client</realm>
        // <summary>When used in a material skin, it returns a color value from a point in the skin image.</summary>
        // <param name="x">X position of the pixel to get the color from.</param>
        // <param name="y">Y position of the pixel to get the color from.</param>
        // <return>table|The color of the point on the skin as a {{Struct|Color}}.</return>
        public virtual table TextureColor(float x, float y) {
            return new table();
        }
    }
}
