//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class input {
        
        // <realm>Client</realm>
        // <summary>Returns the last key captured by key trapping.</summary>
        public static void CheckKeyTrapping() {
        }
        
        // <realm>Client</realm>
        // <summary>Returns the cursor's position on the screen</summary>
        public static void GetCursorPos() {
        }
        
        // <realm>Client</realm>
        // <summary>Gets the name of the key index.</summary>
        // <param name="key">The key, see {{Enum|KEY}}.</param>
        public static void GetKeyName(float key) {
        }
        
        // <realm>Client</realm>
        // <summary>Gets whether a key or mouse button is down. Seems to be a combination of {{LibraryFunction|input|IsKeyDown}} and {{LibraryFunction|input|IsMouseDown}}.</summary>
        // <param name="button">The button, see {{Enum|KEY}} and {{Enum|MOUSE}}.</param>
        public static void IsButtonDown(float button) {
        }
        
        // <realm>Client</realm>
        // <summary>Returns whether a control key is being pressed</summary>
        public static void IsControlDown() {
        }
        
        // <realm>Client</realm>
        // <summary>Gets whether a key is down</summary>
        // <param name="key">The key, see {{Enum|KEY}}.</param>
        public static void IsKeyDown(float key) {
        }
        
        // <realm>Client</realm>
        // <summary>Returns whether key trapping is activate and the next key press will be captured.</summary>
        public static void IsKeyTrapping() {
        }
        
        // <realm>Client</realm>
        // <summary>Gets whether a mouse button is down</summary>
        // <param name="mouseKey">The key, see {{Enum|MOUSE}}.</param>
        public static void IsMouseDown(float mouseKey) {
        }
        
        // <realm>Client</realm>
        // <summary>Gets whether a shift key is being pressed</summary>
        public static void IsShiftDown() {
        }
        
        // <realm>Client</realm>
        // <summary>Gets the match uppercase key for the specified binding.</summary>
        // <param name="binding">The binding name.</param>
        public static void LookupBinding(string binding) {
        }
        
        // <realm>Client</realm>
        // <summary>Sets the cursor's position on the screen, relative to the topleft corner of the window</summary>
        // <param name="mouseX">X coordinate for mouse position.</param>
        // <param name="mouseY">Y coordinate for mouse position.</param>
        public static void SetCursorPos(float mouseX, float mouseY) {
        }
        
        // <realm>Client</realm>
        // <summary>Starts key trap</summary>
        public static void StartKeyTrapping() {
        }
        
        // <realm>Client</realm>
        // <summary>Returns whether a key was initially pressed in the same frame this function was called.</summary>
        // <param name="key">The key, see {{Enum|KEY}}.</param>
        public static void WasKeyPressed(float key) {
        }
        
        // <realm>Client</realm>
        // <summary>Returns whether a key was released in the same frame this function was called.</summary>
        // <param name="key">The key, see {{Enum|KEY}}.</param>
        public static void WasKeyReleased(float key) {
        }
        
        // <realm>Client</realm>
        // <summary>Returns whether the key is being held down or not.</summary>
        // <param name="key">The key to test, see {{Enum|KEY}}.</param>
        public static void WasKeyTyped(float key) {
        }
        
        // <realm>Client</realm>
        // <summary>Returns whether a mouse key was double pressed in the same frame this function was called.<br/></summary>
        // <param name="button">The mouse button to test, see {{Enum|MOUSE}}.</param>
        public static void WasMouseDoublePressed(float button) {
        }
        
        // <realm>Client</realm>
        // <summary>Returns whether a mouse key was initially pressed in the same frame this function was called.<br/></summary>
        // <param name="key">The key, see {{Enum|MOUSE}}.</param>
        public static void WasMousePressed(float key) {
        }
    }
}
