//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class jit {
        
        // <realm>Shared</realm>
        // <summary>You can attach callbacks to a number of compiler events with jit.attach. The callback can be called:</summary>
        // <param name="callback">The callback function.</param>
        // <param name="event">The event to hook into.</param>
        public virtual void attach(function callback, string @event) {
        }
        
        // <realm>Shared</realm>
        // <summary>Flushes the whole cache of compiled code.</summary>
        public virtual void flush() {
        }
        
        // <realm>Shared</realm>
        // <summary>Disables LuaJIT Lua compilation.</summary>
        public virtual void off() {
        }
        
        // <realm>Shared</realm>
        // <summary>Enables LuaJIT Lua compilation.</summary>
        public virtual void on() {
        }
        
        // <realm>Shared</realm>
        // <summary>Returns the status of the JIT compiler and the current optimizations enabled.</summary>
        // <return>boolean|Is JIT enabled</return>
        public virtual bool status() {
            return true;
        }
    }
}
