//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class language {
        
        // <realm>Client</realm>
        // <summary>Adds a language item. Language placeholders are replaced with full text in Garry's Mod once registered with this function.</summary>
        // <param name="placeholder">The key for this phrase.</param>
        // <param name="fulltext">The phrase that should be displayed whenever this key is used.</param>
        public static void Add(string placeholder, string fulltext) {
        }
        
        // <realm>Client</realm>
        // <summary>Retrieves the translated version of inputted string. Useful for concentrating multiple translated strings.</summary>
        // <param name="phrase">The untranslated phrase.</param>
        public static void GetPhrase(string phrase) {
        }
    }
}
