//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class presets {
        
        // <realm>Client</realm>
        // <summary>Adds preset to a preset group.</summary>
        // <param name="groupname">The preset group name, usually it's tool class name.</param>
        // <param name="name">Preset name, must be unique.</param>
        // <param name="values">A table of preset console commands.</param>
        public static void Add(string groupname, string name, table values) {
        }
        
        // <realm>Client</realm>
        // <summary>Returns a table with preset names and values from a single preset group.</summary>
        // <param name="groupname">Preset group name.</param>
        public static void GetTable(string groupname) {
        }
        
        // <realm>Client</realm>
        // <summary>Removes a preset entry from a preset group.</summary>
        // <param name="groupname">Preset group to remove from.</param>
        // <param name="name">Name of preset to remove.</param>
        public static void Remove(string groupname, string name) {
        }
        
        // <realm>Client</realm>
        // <summary>Renames preset.</summary>
        // <param name="groupname">Preset group name.</param>
        // <param name="oldname">Old preset name.</param>
        // <param name="newname">New preset name.</param>
        public static void Rename(string groupname, string oldname, string newname) {
        }
    }
}
