//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// /*  AutoGeneratedCode.cs - This class Is autogenerated.
//
//    Copyright (C) 2014  Ali Deym (https://github.com/111WARLOCK111/).
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//*/
namespace MetroMad.Lua.gLua {
    using System;
    
    
    public class weapons {
        
        // <realm>Shared</realm>
        // <summary>Get copy of weapon table by name.</summary>
        // <param name="classname">Class name of weapon to retrieve.</param>
        // <return>table|The retrieved table or nil</return>
        public virtual table Get(string classname) {
            return new table();
        }
        
        // <realm>Shared</realm>
        // <summary>Get a list of all the registered SWEPs. This does not include weapons added to spawnmenu manually.</summary>
        // <return>table|List of all the registered SWEPs</return>
        public virtual table GetList() {
            return new table();
        }
        
        // <realm>Shared</realm>
        // <summary>Gets the REAL weapon table, not a copy.</summary>
        // <param name="weapon_class">Weapon class to retrieve weapon table of.</param>
        // <return>table|The weapon table</return>
        public virtual table GetStored(string weapon_class) {
            return new table();
        }
        
        // <realm>Shared</realm>
        // <summary>Called after all SWEPS have been loaded.</summary>
        public virtual void OnLoaded() {
        }
        
        // <realm>Shared</realm>
        // <summary>Used to register your SWEP with the engine.</summary>
        // <param name="swep_table">The SWEP table.</param>
        // <param name="classname">Classname to assign to that swep.</param>
        public virtual void Register(table swep_table, string classname) {
        }
    }
}
